[project]
name = "decorrelation-stretch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "reya", email = "bennett.mertz@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "opencv-python>=5.0.0.93",
]

[project.scripts]
decorrelation-stretch = "decorrelation_stretch:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
